insert into public.categories (name, slug, description, sort_order)
values
  ('Classic Butter', 'classic-butter', 'Everyday nut butters made with familiar, deeply roasted nuts.', 10),
  ('Smooth Spreads', 'smooth-spreads', 'Velvety spreads with a naturally sweet finish.', 20),
  ('Exotic Blends', 'exotic-blends', 'Small-batch blends made from rarer nuts and richer profiles.', 30)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order,
  is_active = true;

insert into public.products (
  category_id,
  sku,
  slug,
  name,
  description,
  ingredients,
  nutrition,
  image_url,
  price,
  currency,
  weight_grams,
  variants,
  stock_quantity,
  is_featured,
  badge,
  badge_style,
  rating,
  reviews_count,
  search_keywords
)
values
  (
    (select id from public.categories where slug = 'classic-butter'),
    'ANC-ALM-250',
    'almond-butter',
    'Almond Butter',
    'Smooth stone-ground roasted almonds, rich in Vitamin E.',
    array['Slow-roasted almonds', 'Himalayan sea salt'],
    '{"protein":"6g","healthy_fats":"14g","fiber":"4g","calories":"190"}'::jsonb,
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDyBN-Z0Mjeayngib0w9mfW_781jpv6wFtLVhons8uN4-dX8cB34oljEiodmF4CPmIuaoZXOHvUWVgQ-3m-edI8CXn4MOHh2KUvvMtVmyyfwamwNT19uPRJowmctiD7Quxa4deJ0ZZtRx_Xkhx1c1d_f1vH1pR7LcWldW7gKqzI77F7TdN0vv9VViQ9gbxOTj6ALWDiKky2_0VoBoZIruzLCceWooJyCRAE1sxfZpeyFoqE3CsWn9ii_0ktI9HqPBT8DtD7Nhdj490',
    549,
    'INR',
    250,
    '[{"label":"250g","price":549},{"label":"500g","price":999}]'::jsonb,
    48,
    true,
    'Bestseller',
    'bg-black/20 backdrop-blur-md text-white',
    4.9,
    124,
    array['almond', 'classic', 'protein']
  ),
  (
    (select id from public.categories where slug = 'smooth-spreads'),
    'ANC-CAS-250',
    'cashew-butter',
    'Cashew Butter',
    'Creamy texture with a naturally sweet hint.',
    array['Roasted cashews', 'Himalayan sea salt'],
    '{"protein":"5g","healthy_fats":"13g","fiber":"2g","calories":"185"}'::jsonb,
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDF9FrD0JlDNJbalfOjmX--iquz5p3MwTsT7ydZeQ5Ekt9KgeTQo0m4zFagxdA2PINFiQexcNoGFggWMTfk-sTNEQfUY5dCd4HWzk-2zkEnrPrg_HV0pbIbhQcb7ONRWxamheP5fBxXD8Ue_6_DZS_A10807yY1LuoOwbpHT3FrOTgZkR2DH_LAGwGu03e6pQmE6WrmUrL9tyTEb_OTdHSqrRuopc0uR8sLwKg3wXNk0ebc6DcczBoeYlNVkt2AQLJxUVo7Gkxrxho',
    699,
    'INR',
    250,
    '[{"label":"250g","price":699},{"label":"500g","price":1299}]'::jsonb,
    36,
    true,
    'Velvety Smooth',
    'bg-black/20 backdrop-blur-md text-white',
    4.8,
    98,
    array['cashew', 'smooth', 'sweet']
  ),
  (
    (select id from public.categories where slug = 'classic-butter'),
    'ANC-PEA-250',
    'peanut-butter',
    'Peanut Butter',
    'Extra crunchy, dark roasted perfection.',
    array['Dark-roasted peanuts', 'Himalayan sea salt'],
    '{"protein":"8g","healthy_fats":"16g","fiber":"3g","calories":"205"}'::jsonb,
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDfo-eScCAtiXawPnWNN5gOOZnw9U98Nb77m5tsohuoC3O4zYAkmKq9OW1CBx2CSMXANZKVbvcYw5jYXqf4MgZ1KxHgr_UC4k-NlkhqV7J8T07GTHPTz_Wr2c-2z9ClNWlpYZus16ZTTfJm3KzyARVybasWFnJV6P9wuwxkFhu_r6pGTZKIdxx_ZV74Y0nNq1EFhu_pu9nZEI6trrVsf7Jm_9NhFgG6XD9Jyx01W3CxDnHY3ocoBxQhVhUVEtwiF17IAjwVDLwY8rI',
    349,
    'INR',
    250,
    '[{"label":"250g","price":349},{"label":"500g","price":649}]'::jsonb,
    72,
    true,
    'Classic',
    'bg-black/20 backdrop-blur-md text-white',
    5.0,
    215,
    array['peanut', 'classic', 'crunchy']
  ),
  (
    (select id from public.categories where slug = 'exotic-blends'),
    'ANC-PIS-250',
    'pistachio-butter',
    'Pistachio Butter',
    'Rare Iranian pistachios, lightly salted.',
    array['Pistachios', 'Himalayan sea salt'],
    '{"protein":"6g","healthy_fats":"15g","fiber":"3g","calories":"198"}'::jsonb,
    'https://lh3.googleusercontent.com/aida-public/AB6AXuCXnP40_r4XU4i3NIAMoBRcyipbK7uibsWFZC7y9qqDNlYNeu0BEtA_sjfVzpnLoHCcCuvVqLnL83aqyJuuoiMNsw-st-B_5QtHM62dEBk64lc9dAOrTgxkAaGiUVlqbmeEqbCFuosQGv-KkjPe1DqDVLLNiubElw3nQr-y6lXkbU7S6pFZaPOfHGZEiRmOu97TYOknFe8HUaM8KhzurW9zYsnYz-PQPS8RWvV0LV6WXZAjSgdLn0MljlGvYPQT0wVgg-lQCqfQBeg',
    1249,
    'INR',
    250,
    '[{"label":"250g","price":1249},{"label":"500g","price":2399}]'::jsonb,
    14,
    true,
    'Limited Edition',
    'bg-black/20 backdrop-blur-md text-white',
    4.9,
    42,
    array['pistachio', 'limited', 'exotic']
  ),
  (
    (select id from public.categories where slug = 'exotic-blends'),
    'ANC-WAL-250',
    'walnut-butter',
    'Walnut Butter',
    'Omega-3 rich, earthy and deeply satisfying.',
    array['Roasted walnuts', 'Himalayan sea salt'],
    '{"protein":"5g","healthy_fats":"18g","fiber":"2g","calories":"210"}'::jsonb,
    'https://lh3.googleusercontent.com/aida-public/AB6AXuC24uXEd6-l4vGGkedO1g6_vFxGsZlu0PmznLeVZUjZoQgI8cVbRBLocqhmrRalHJVVgmeLi5MHJn7_iPdDmpbUviBG01MD1JVrjSOnDA2DqfB1JjzJoGz7k7aUFqcKUxsuWmOYg9M_Hta0utV926GAaBzDuaRRc3eq_WsLfKQz6F3lUeImCF6hJrRNdWEaYdJGGQisCz7FrhhXPP6pyAiNPjit-QH_-WxfkvrsSad2-u--ATIS5_xqduyVoRgnCQZRTQcxFPNsVF4',
    899,
    'INR',
    250,
    '[{"label":"250g","price":899},{"label":"500g","price":1699}]'::jsonb,
    21,
    false,
    null,
    null,
    4.7,
    56,
    array['walnut', 'omega', 'exotic']
  ),
  (
    (select id from public.categories where slug = 'classic-butter'),
    'ANC-HAZ-250',
    'hazelnut-butter',
    'Hazelnut Butter',
    'Rich, toasty and naturally sweet hazelnut spread.',
    array['Roasted hazelnuts', 'Himalayan sea salt'],
    '{"protein":"4g","healthy_fats":"17g","fiber":"3g","calories":"202"}'::jsonb,
    'https://lh3.googleusercontent.com/aida-public/AB6AXuAn1c-ltZ-IkHTsAk1o2OdREgzE25K15OHpdtfp4Kj10DBaXr0ng6i-Xez0JxxxPqwmi6jvp6BpdJLjj8l1ltwPa3am9Kp4DsAvmP9He-um91_ODiiV0ZRvx0obnqYF1kHX_yBhdFAvF8sdfh3CFQQCFcdoGzY810XlI_lrsHRZX5JlbB3RpDettcZ4QBZdWL4RUE5gE-tbDPzsJaDbhc8crlwKxbgSRCz900bkxY_5ETANb7igKbakecrJBRXbzaLQv9p9dDEv-nM',
    799,
    'INR',
    250,
    '[{"label":"250g","price":799},{"label":"500g","price":1499}]'::jsonb,
    28,
    false,
    'New',
    'bg-secondary text-on-secondary',
    4.8,
    31,
    array['hazelnut', 'classic', 'new']
  )
on conflict (slug) do update set
  category_id = excluded.category_id,
  sku = excluded.sku,
  name = excluded.name,
  description = excluded.description,
  ingredients = excluded.ingredients,
  nutrition = excluded.nutrition,
  image_url = excluded.image_url,
  price = excluded.price,
  currency = excluded.currency,
  weight_grams = excluded.weight_grams,
  variants = excluded.variants,
  stock_quantity = excluded.stock_quantity,
  is_featured = excluded.is_featured,
  badge = excluded.badge,
  badge_style = excluded.badge_style,
  rating = excluded.rating,
  reviews_count = excluded.reviews_count,
  search_keywords = excluded.search_keywords,
  is_active = true;

insert into public.reviews (product_id, customer_name, title, body, rating, is_verified_purchase, is_published)
values
  ((select id from public.products where slug = 'almond-butter'), 'Elena R.', 'Stone-ground difference', 'The stone-ground difference is real. Rich, smooth, and beautifully roasted.', 5, true, true),
  ((select id from public.products where slug = 'almond-butter'), 'Marcus Thorne', 'Pure ingredients', 'Pure ingredients and an incredible roast profile. You can taste the almond quality.', 5, true, true),
  ((select id from public.products where slug = 'cashew-butter'), 'Sarah Jenkins', 'So creamy', 'Finally a cashew butter that stays creamy without palm oil.', 5, true, true)
on conflict do nothing;

