/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    'md:flex-row','md:w-64','md:w-1/3','md:w-1/2','md:grid-cols-4','md:flex',
    'sm:flex-row','sm:grid-cols-2','lg:grid-cols-2','lg:grid-cols-3','lg:grid-cols-4',
    'group-hover:scale-105','hover:shadow-lg','hover:bg-black','hover:opacity-90',
    'hover:text-[#A67B5B]','hover:text-[#4B3621]','hover:bg-surface-container',
    'hover:bg-secondary','hover:text-on-secondary',
    'active:scale-95','transition-transform','transition-colors','transition-all',
    'duration-300','duration-500','aspect-[4/5]','aspect-square',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dfd9d1',
        'surface-container-high': '#ede7de',
        'surface-bright': '#fff9ef',
        'secondary-fixed': '#ffdcc4',
        'on-tertiary-fixed': '#231a08',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#b2a288',
        'on-tertiary-fixed-variant': '#504530',
        'surface-tint': '#725a42',
        'on-secondary-fixed-variant': '#613f24',
        'secondary-fixed-dim': '#efbc98',
        'primary-fixed-dim': '#e1c1a4',
        'on-surface-variant': '#4e453d',
        'on-error-container': '#93000a',
        'primary-container': '#4b3621',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e7e2d9',
        'outline-variant': '#d2c4ba',
        'on-primary-fixed-variant': '#59422c',
        'on-primary-fixed': '#291806',
        'primary': '#33210d',
        'surface-container-low': '#f9f3ea',
        'on-surface': '#1d1b16',
        'primary-fixed': '#fedcbe',
        'surface': '#fff9ef',
        'inverse-on-surface': '#f6f0e7',
        'surface-container': '#f3ede4',
        'error': '#ba1a1a',
        'on-secondary-container': '#795336',
        'secondary': '#7c5639',
        'surface-container-highest': '#e7e2d9',
        'tertiary': '#2c2310',
        'background': '#fff9ef',
        'outline': '#80756c',
        'on-error': '#ffffff',
        'secondary-container': '#fecaa5',
        'inverse-surface': '#32302a',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#d5c5a8',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#f2e0c3',
        'tertiary-container': '#433924',
        'on-primary-container': '#bd9f83',
        'on-secondary-fixed': '#2f1501',
        'inverse-primary': '#e1c1a4',
        'on-background': '#1d1b16',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '12px',
        gutter: '24px',
        md: '24px',
        base: '8px',
        margin: '32px',
        lg: '48px',
        xs: '4px',
        xl: '80px',
      },
      fontFamily: {
        serif: ['Noto Serif', 'serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm':    ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-md':     ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md':    ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg':     ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
