export const SUPABASE_TABLES = {
  profiles: 'profiles',
  products: 'products',
  categories: 'categories',
  cartItems: 'cart_items',
  orders: 'orders',
  orderItems: 'order_items',
  payments: 'payments',
  checkoutSessions: 'checkout_sessions',
  checkoutSessionItems: 'checkout_session_items',
  shipments: 'shipments',
  addresses: 'addresses',
  reviews: 'reviews',
  contactMessages: 'contact_messages',
  newsletterSubscribers: 'newsletter_subscribers',
  adminRoles: 'admin_roles',
  coupons: 'coupons',
  orderTimelineEvents: 'order_timeline_events',
  emailEvents: 'email_events',
}
